import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Generated by `npx shadcn add` and overwritten on every re-add, so fixing
    // these in place does not stick. Two rules fire on the upstream source:
    // components export their `cva` variants alongside the component itself
    // (react-refresh), and `use-mobile` seeds its state from a synchronous
    // effect (set-state-in-effect). Both are upstream's call to make, not ours.
    files: ['src/components/ui/**/*.tsx', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // Same deal, for the larger blocks pulled from the reui registry (filters,
    // cascader, event calendar, gantt, kanban, file upload): also regenerated
    // wholesale by `npx shadcn add`, so a local fix does not survive the next
    // update. The React Compiler–oriented hook rules (refs/purity/
    // immutability/preserve-manual-memoization/exhaustive-deps) fire on ref-
    // during-render and dependency patterns that are idiomatic in this
    // (pre-Compiler) codebase but that the rule set assumes are gone.
    files: [
      'src/components/reui/**/*.tsx',
      'src/components/examples/**/*.tsx',
      'src/hooks/use-file-upload.ts',
    ],
    // The vendor's own inline `eslint-disable exhaustive-deps` comments are
    // now redundant since the rule is off here project-wide — that would
    // otherwise warn as an unused directive.
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/exhaustive-deps': 'off',
      // `_e`/`_de`/etc: deliberately unused destructured params naming a
      // shape the callback signature must match, plus one stray `any` and
      // an unused prop kept for a symmetric call signature across variants.
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
