import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Generated by `npx shadcn add` and overwritten on every re-add, so fixing
    // these in place does not stick. Two rules fire on the upstream source:
    // components export their `cva` variants alongside the component itself
    // (react-refresh), and `use-mobile` seeds its state from a synchronous
    // effect (set-state-in-effect). Both are upstream's call to make, not ours.
    files: ['src/components/ui/**/*.tsx', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
])
