/**
 * Builds src/theme/tokens.css from src/theme/colors.ts (the single source of
 * truth). Run via `npm run theme` — wired into dev/build. Never edit
 * tokens.css by hand; if it drifts, run this.
 *
 * Also enforces CONTRAST_CONTRACT: if any guaranteed foreground/background pair
 * drops below its WCAG threshold, the build fails here rather than shipping a
 * regression nobody notices. This is what stops the class of bug where a token
 * is picked to "look subtle" and quietly lands under 4.5:1 (or under 3:1 for a
 * border that is the only thing identifying a control's boundary).
 *
 * Requires Node ≥ 22.6 (native TS type-stripping); colors.ts uses only
 * erasable TypeScript.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tokens, cssVarName, checkContrast, CONTRAST_CONTRACT } from '../src/theme/colors.ts';

const MODES = ['light', 'dark'];

// ── Gate: contrast contract ─────────────────────────────────────────────────
let failed = false;
for (const mode of MODES) {
  const failures = checkContrast(mode);
  if (failures.length === 0) {
    console.log(`✓ contrast: ${mode} passes all ${CONTRAST_CONTRACT.length} contracted pairs`);
    continue;
  }
  failed = true;
  console.error(`\n✗ contrast: ${mode} has ${failures.length} failing pair(s):`);
  for (const { pair, ratio, min } of failures) {
    console.error(`    ${pair} — ${ratio.toFixed(2)}:1, needs ${min}:1`);
  }
}

if (failed) {
  console.error('\nFix the values in src/theme/colors.ts. tokens.css was NOT regenerated.\n');
  process.exit(1);
}

// ── Emit ────────────────────────────────────────────────────────────────────
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(root, 'src', 'theme', 'tokens.css');

const lines = (mode) =>
  Object.entries(tokens)
    .map(([name, value]) => `  ${cssVarName(name)}: ${value[mode]};`)
    .join('\n');

const css = `/* AUTO-GENERATED by scripts/build-theme.mjs - DO NOT EDIT.
   Source of truth: src/theme/colors.ts (run \`npm run theme\` to regenerate). */

:root {
${lines('light')}
}

.dark {
${lines('dark')}
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css, 'utf8');
console.log(`✓ wrote ${outPath}`);
