import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Build-time execution context since this is an ES module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Since we just simplified colors.ts to not have contrast checkers (for speed),
// we will just parse it and emit the CSS directly.
import { tokens } from '../src/theme/colors.ts';

const outPath = path.join(__dirname, '..', 'src', 'theme', 'tokens.css');

let css = `/* AUTO-GENERATED by scripts/build-theme.mjs — DO NOT EDIT */\n\n:root {\n`;

for (const [key, val] of Object.entries(tokens)) {
  css += `  --${key}: ${val.dark};\n`;
}

css += `}\n`;

fs.writeFileSync(outPath, css);
console.log('✓ wrote ' + outPath);
