/**
 * Emits `src/theme/tokens.css` from `src/theme/colors.ts`, and enforces the
 * §3 Contrast Contract before writing. Runs on every `npm run dev` and
 * `npm run build` — a failing pair exits non-zero and stops the build.
 *
 * AGENTS.md §3: "A checker that compares raw token values will silently skip
 * every rgba() token, which is precisely where the borders, tints, and focus
 * ring live. The contract is only meaningful if alpha values are composited
 * over each background before measuring."
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { tokens, parseColor, composite, contrastRatio } from '../src/theme/colors.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '..', 'src', 'theme', 'tokens.css');

/* ── Resolve `var(--x)` chains down to a literal color ──────────────────── */

function literal(name, seen = new Set()) {
  const raw = tokens[name];
  if (raw === undefined) throw new Error(`Unknown token: --${name}`);
  const ref = /^var\(--([a-z0-9-]+)\)$/i.exec(raw.trim());
  if (!ref) return raw;
  if (seen.has(name)) throw new Error(`Circular token reference at --${name}`);
  seen.add(name);
  return literal(ref[1], seen);
}

/** Contrast of token `fg` against token `bg`, both composited over `over`. */
function pairRatio(fg, bg, over) {
  const base = parseColor(literal(over));
  const f = parseColor(literal(fg));
  const b = parseColor(literal(bg));
  if (!f || !b || !base) {
    throw new Error(`Unparseable color in pair --${fg} on --${bg} over --${over}`);
  }
  const solidBg = composite(b, base);
  return contrastRatio(composite(f, solidBg), solidBg);
}

/* ── The contract ───────────────────────────────────────────────────────── */

const SURFACES = ['bg-canvas', 'bg-surface', 'bg-surface-raised'];
const RAMPS = ['primary', 'success', 'warning', 'danger', 'special'];

const contract = [];

// Body text on every surface — WCAG 1.4.3.
for (const fg of ['text-primary', 'text-secondary', 'text-muted']) {
  for (const bg of SURFACES) contract.push({ fg, bg, over: bg, min: 4.5 });
}

// Interactive boundaries and the focus ring — WCAG 1.4.11 / 2.4.11.
for (const fg of ['border-default', 'border-strong', 'primary']) {
  for (const bg of SURFACES) contract.push({ fg, bg, over: bg, min: 3 });
}

// Each ramp's foreground on its filled base.
for (const ramp of RAMPS) {
  contract.push({ fg: `${ramp}-foreground`, bg: ramp, over: 'bg-surface', min: 4.5 });
}

// Each ramp's on-muted text on its 15% tint, over canvas AND surface.
for (const ramp of RAMPS) {
  for (const over of ['bg-canvas', 'bg-surface']) {
    contract.push({ fg: `${ramp}-on-muted`, bg: `${ramp}-muted`, over, min: 4.5 });
  }
}

// --text-disabled is deliberately absent: WCAG 1.4.3 exempts disabled controls,
// and forcing contrast there defeats the disabled affordance.

/* ── Verify ─────────────────────────────────────────────────────────────── */

const failures = [];
for (const { fg, bg, over, min } of contract) {
  const r = pairRatio(fg, bg, over);
  if (r + 1e-9 < min) {
    failures.push(
      `  --${fg} on --${bg} (over --${over}): ${r.toFixed(2)}:1, needs ${min}:1`,
    );
  }
}

if (failures.length > 0) {
  console.error(
    `\n✗ Contrast contract violated — ${failures.length} of ${contract.length} pairs failed:\n` +
      failures.join('\n') +
      '\n\nFix the token values in src/theme/colors.ts (AGENTS.md §3).\n',
  );
  process.exit(1);
}

/* ── Emit ───────────────────────────────────────────────────────────────── */

let css = '/* AUTO-GENERATED by scripts/build-theme.mjs — DO NOT EDIT */\n\n:root {\n';
for (const [key, value] of Object.entries(tokens)) {
  css += `  --${key}: ${value};\n`;
}
css += '}\n';

fs.writeFileSync(outPath, css);
console.log(
  `✓ contrast contract: ${contract.length}/${contract.length} pairs pass\n` +
    `✓ wrote ${outPath}`,
);
